SELECT 
    YEAR(os.SALES_DATE) AS YEAR,
    MONTH(os.SALES_DATE) AS MONTH,
    COUNT(DISTINCT ui.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT ui.USER_ID)
        /
        (SELECT COUNT(*)
         FROM USER_INFO
         WHERE YEAR(JOINED) = 2021)
    , 1) AS PUCHASED_RATIO
FROM USER_INFO ui
JOIN ONLINE_SALE os
    ON os.USER_ID = ui.USER_ID
WHERE YEAR(ui.JOINED) = 2021
  AND YEAR(os.SALES_DATE) = 2022
GROUP BY YEAR(os.SALES_DATE), MONTH(os.SALES_DATE)
ORDER BY YEAR, MONTH;